project:
  type: website
  output-dir: docs

execute:
  cache: true
  freeze: true 

website:
  favicon: "favicon.ico"
  back-to-top-navigation: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    title: "StatTogether"
    logo: "logo2.png"
    background: "#0077b6"
    search: true
    left:
      - text: "Ensai 2A"
        menu:
          - text: "Projet statistique"
            href: projets/LAL/lal.qmd
          - text: "Apprentissage supervisé"
            href: projets/app_supervise/Tp_Cheryl_Kouadio.Rmd
          - text: "Microénométrie"
            href: projets/micro/micro_notes.qmd
          - text: "Statistiques non paramétriques"
            href: projets/np_stat/np_stat_notes.qmd
          - text: "Séries temporelles 1"
            href: projets/TS/ts1.Rmd
      - text: "Gestion des risques"
        menu:
          - text: "i - Le bilan d'entreprise"
            href: articles/GDR/bilan_entreprise.qmd
          - text: "ii - Les Accords de Bâle"
            href: articles/GDR/resume_reglementation.qmd
          - text: "iii - Définition du risque"
            href: articles/GDR/risque_def.qmd
          - text: "1-La réglementation prudentielle"
            href: articles/GDR/reglementation_prudentielle.qmd
          - text: "2-La valeur en risque"
            href: articles/GDR/var.qmd
          - text: "2.1 - Application VaR"
            href: articles/GDR/VaR_eg.qmd
      - text: "Divers"
        menu:
          - text: "Investissement socialement responsable"
            href: articles/ISR/ISR.qmd
          - text: "Improve Speaking Fluency"
            href: articles/4-3-2/fluency.qmd
    right:
      - text: "A propos"
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/cheryl-kouadio-251815206/
      - icon: github
        menu:
          - text: "Profile"
            url: https://github.com/cheryl-kdio
          - text: "Source Code"
            url: https://code.com
          - text: "Report a Bug"
            url: https://bugs.com

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    toc: true
    toc-location: left
    toc-title: "Sur cette page"
    df-print: kable

editor: visual
