project:
  type: website

execute:
  cache: true
  freeze: true 

website:
  title: "We Stat"
  favicon: "favicon.ico"
  back-to-top-navigation: true
  sidebar:
    background: "#fff0f3"
    #logo: "favicon.ico"
    style: "docked"
    contents:
      - section: "Projet 2A"
        contents:
          - href: projets/LAL/lal.qmd
            text : Projet statistique
          - href : projets/app_supervise/Tp_Cheryl_Kouadio.Rmd
            text : Apprentissage supervisé
          - section: "Séries temporelles"
            contents:
              - href : projets/TS/ts1.Rmd
                text : Series temporelles 1
      - section: "Projets 3A"
      - section: "Articles"
        contents:
          - href : articles/ISR/ISR.qmd
            text : Investissement socialement responsable
          - href : articles/Bourse/indice_boursier.qmd
            text : Les indices boursiers


  navbar:
    title: "We Stat"
    search: true
    background: "#a4133c"
    right:
      - text: A propos
        href: about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/cheryl-kouadio-251815206/
      - icon: github
        menu:
          - text: Profile
            url: https://github.com/cheryl-kdio
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: kable

editor: visual

